# Site settings
title: domogalla.org
email: jason@domogalla.org
description: "A small site showcasing the work of Jason Domogalla."
baseurl: "" # the subpath of your site, e.g. /blog/
s3url: "https://s3-us-west-2.amazonaws.com/domogalla/"
url: "http://domogalla.org" # the base hostname & protocol for your site
twitter_username: jomogalla
github_username:  jomogalla
instagram_username:  jomogalla
tumblr_username:  fieldguidetobirds
collections:
    stories:
        output: true
    webwork:
        output: true

# Build settings
markdown: kramdown
