# Site settings
title: domogalla.org
email: jason@domogalla.org
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
s3url: "https://s3-us-west-2.amazonaws.com/domogalla/"
url: "http://domogalla.org" # the base hostname & protocol for your site
twitter_username: jomogalla
github_username:  jomogalla
instagram_username:  jomogalla
tumblr_username:  fieldguidetobirds
collections:
    stories:
        output: true
    webwork:
        output: true

# Build settings
markdown: kramdown
